/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  EnvironmentsApi,
  JobsApi,
  NodesApi,
  RunsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { CoalesceCustom } from "./client-custom";

export class Coalesce extends CoalesceCustom {
  readonly environments: EnvironmentsApi;
  readonly jobs: JobsApi;
  readonly nodes: NodesApi;
  readonly runs: RunsApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.environments = new EnvironmentsApi(configuration);
    this.jobs = new JobsApi(configuration);
    this.nodes = new NodesApi(configuration);
    this.runs = new RunsApi(configuration);
  }

}
