/* tslint:disable */
/* eslint-disable */
/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ErrorResponse } from '../models';
// @ts-ignore
import { Node } from '../models';
// @ts-ignore
import { NodesResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * NodesApi - axios parameter creator
 * @export
 */
export const NodesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get information about a node in an environment.
         * @summary Get Node
         * @param {string} environmentID The environment ID.
         * @param {string} nodeID The node ID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInformation: async (environmentID: string, nodeID: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'environmentID' is not null or undefined
            assertParamExists('getInformation', 'environmentID', environmentID)
            // verify required parameter 'nodeID' is not null or undefined
            assertParamExists('getInformation', 'nodeID', nodeID)
            const localVarPath = `/api/v1/environments/{environmentID}/nodes/{nodeID}`
                .replace(`{${"environmentID"}}`, encodeURIComponent(String(environmentID !== undefined ? environmentID : `-environmentID-`)))
                .replace(`{${"nodeID"}}`, encodeURIComponent(String(nodeID !== undefined ? nodeID : `-nodeID-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/api/v1/environments/{environmentID}/nodes/{nodeID}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a collection of nodes for an environment
         * @summary List Nodes
         * @param {string} environmentID The environment ID.
         * @param {boolean} [detail] Include the full detail of the nodes.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list: async (environmentID: string, detail?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'environmentID' is not null or undefined
            assertParamExists('list', 'environmentID', environmentID)
            const localVarPath = `/api/v1/environments/{environmentID}/nodes`
                .replace(`{${"environmentID"}}`, encodeURIComponent(String(environmentID !== undefined ? environmentID : `-environmentID-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (detail !== undefined) {
                localVarQueryParameter['detail'] = detail;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/api/v1/environments/{environmentID}/nodes',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NodesApi - functional programming interface
 * @export
 */
export const NodesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NodesApiAxiosParamCreator(configuration)
    return {
        /**
         * Get information about a node in an environment.
         * @summary Get Node
         * @param {NodesApiGetInformationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInformation(requestParameters: NodesApiGetInformationRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Node>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getInformation(requestParameters.environmentID, requestParameters.nodeID, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get a collection of nodes for an environment
         * @summary List Nodes
         * @param {NodesApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async list(requestParameters: NodesApiListRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NodesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.list(requestParameters.environmentID, requestParameters.detail, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * NodesApi - factory interface
 * @export
 */
export const NodesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NodesApiFp(configuration)
    return {
        /**
         * Get information about a node in an environment.
         * @summary Get Node
         * @param {NodesApiGetInformationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInformation(requestParameters: NodesApiGetInformationRequest, options?: AxiosRequestConfig): AxiosPromise<Node> {
            return localVarFp.getInformation(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a collection of nodes for an environment
         * @summary List Nodes
         * @param {NodesApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list(requestParameters: NodesApiListRequest, options?: AxiosRequestConfig): AxiosPromise<NodesResponse> {
            return localVarFp.list(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getInformation operation in NodesApi.
 * @export
 * @interface NodesApiGetInformationRequest
 */
export type NodesApiGetInformationRequest = {
    
    /**
    * The environment ID.
    * @type {string}
    * @memberof NodesApiGetInformation
    */
    readonly environmentID: string
    
    /**
    * The node ID.
    * @type {string}
    * @memberof NodesApiGetInformation
    */
    readonly nodeID: string
    
}

/**
 * Request parameters for list operation in NodesApi.
 * @export
 * @interface NodesApiListRequest
 */
export type NodesApiListRequest = {
    
    /**
    * The environment ID.
    * @type {string}
    * @memberof NodesApiList
    */
    readonly environmentID: string
    
    /**
    * Include the full detail of the nodes.
    * @type {boolean}
    * @memberof NodesApiList
    */
    readonly detail?: boolean
    
}

/**
 * NodesApiGenerated - object-oriented interface
 * @export
 * @class NodesApiGenerated
 * @extends {BaseAPI}
 */
export class NodesApiGenerated extends BaseAPI {
    /**
     * Get information about a node in an environment.
     * @summary Get Node
     * @param {NodesApiGetInformationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NodesApiGenerated
     */
    public getInformation(requestParameters: NodesApiGetInformationRequest, options?: AxiosRequestConfig) {
        return NodesApiFp(this.configuration).getInformation(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get a collection of nodes for an environment
     * @summary List Nodes
     * @param {NodesApiListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NodesApiGenerated
     */
    public list(requestParameters: NodesApiListRequest, options?: AxiosRequestConfig) {
        return NodesApiFp(this.configuration).list(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
