/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TagColor } from './tag-color';

/**
 * An environment is used for deploying your data pipeline to non-development Snowflake environments.
 * @export
 * @interface BaseEnvironment
 */
export interface BaseEnvironment {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof BaseEnvironment
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseEnvironment
     */
    'connectionAccount'?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseEnvironment
     */
    'defaultStorageMapping'?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseEnvironment
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BaseEnvironment
     */
    'oauthEnabled'?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof BaseEnvironment
     */
    'runTimeParameters'?: { [key: string]: any; };
    /**
     * 
     * @type {TagColor}
     * @memberof BaseEnvironment
     */
    'tagColors'?: TagColor;
    /**
     * 
     * @type {string}
     * @memberof BaseEnvironment
     */
    'project'?: string;
}

