/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DeployRunDetails
 */
export interface DeployRunDetails {
    /**
     * 
     * @type {boolean}
     * @memberof DeployRunDetails
     */
    'canceled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DeployRunDetails
     */
    'deployCommit': string;
    /**
     * 
     * @type {string}
     * @memberof DeployRunDetails
     */
    'deployCommitMessage'?: string;
    /**
     * 
     * @type {string}
     * @memberof DeployRunDetails
     */
    'environmentID': string;
    /**
     * 
     * @type {number}
     * @memberof DeployRunDetails
     */
    'parallelism'?: number;
    /**
     * 
     * @type {number}
     * @memberof DeployRunDetails
     */
    'nodesInRun'?: number;
}

