/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnvironmentsResponseData } from './environments-response-data';

/**
 * 
 * @export
 * @interface EnvironmentsResponse
 */
export interface EnvironmentsResponse {
    /**
     * 
     * @type {EnvironmentsResponseData}
     * @memberof EnvironmentsResponse
     */
    'data': EnvironmentsResponseData;
}

