/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @enum {string}
 */
export type EnvironmentHealth = 'Deleting' | 'Deploying' | 'Failed Deploy' | 'Failed Dev Run' | 'Failed Refresh' | 'Initializing' | 'Refreshing' | 'Running Dev Run' | 'Waiting'

