/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BaseEnvironment } from './base-environment';
import { EnvironmentSummary } from './environment-summary';

/**
 * @type EnvironmentsResponseData
 * A collection of environment information.
 * @export
 */
export type EnvironmentsResponseData = Array<EnvironmentSummary> | Array<BaseEnvironment>;


