/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EnvironmentStorageLocationMappingsValue
 */
export interface EnvironmentStorageLocationMappingsValue {
    /**
     * 
     * @type {string}
     * @memberof EnvironmentStorageLocationMappingsValue
     */
    'database'?: string;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentStorageLocationMappingsValue
     */
    'schema'?: string;
}

