/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ColumnReference } from './column-reference';
import { HashAlgorithm } from './hash-algorithm';

/**
 * 
 * @export
 * @interface HashMetadata
 */
export interface HashMetadata {
    /**
     * 
     * @type {HashAlgorithm}
     * @memberof HashMetadata
     */
    'hashAlgorithm': HashAlgorithm;
    /**
     * 
     * @type {string}
     * @memberof HashMetadata
     */
    'hashType'?: HashMetadataHashTypeEnum;
    /**
     * 
     * @type {Array<ColumnReference>}
     * @memberof HashMetadata
     */
    'hubHashes'?: Array<ColumnReference>;
}

type HashMetadataHashTypeEnum = 'ChangeHash' | 'Hash' | 'HubHash' | 'LinkHash' | 'None'


