/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface JobsCancelJobRunRequest
 */
export interface JobsCancelJobRunRequest {
    /**
     * The ID of the run the user would like to cancel.
     * @type {number}
     * @memberof JobsCancelJobRunRequest
     */
    'runID': number;
    /**
     * The organization\'s ID of the run the user would like to cancel.
     * @type {string}
     * @memberof JobsCancelJobRunRequest
     */
    'orgID'?: string;
    /**
     * The environment ID of the run the user would like to cancel.
     * @type {string}
     * @memberof JobsCancelJobRunRequest
     */
    'environmentID'?: string;
}

