/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Object containing the necessary target details required to successfully start a refresh.
 * @export
 * @interface JobsInitiateRunRequestRunDetails
 */
export interface JobsInitiateRunRequestRunDetails {
    /**
     * The environment being refreshed
     * @type {string}
     * @memberof JobsInitiateRunRequestRunDetails
     */
    'environmentID': string;
    /**
     * Nodes included for an ad-hoc job
     * @type {string}
     * @memberof JobsInitiateRunRequestRunDetails
     */
    'includeNodesSelector'?: string;
    /**
     * Nodes excluded for an ad-hoc job.
     * @type {string}
     * @memberof JobsInitiateRunRequestRunDetails
     */
    'excludeNodesSelector'?: string;
    /**
     * The ID of a job being run.
     * @type {string}
     * @memberof JobsInitiateRunRequestRunDetails
     */
    'jobID'?: string;
    /**
     * Maximum number of parallel nodes to run.
     * @type {number}
     * @memberof JobsInitiateRunRequestRunDetails
     */
    'parallelism'?: number;
    /**
     * Allows refreshing an environment even if the last deployment on that environment failed. Use with caution as this can put your environment into an even worse state.
     * @type {boolean}
     * @memberof JobsInitiateRunRequestRunDetails
     */
    'forceIgnoreWorkspaceStatus'?: boolean;
}

