/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobsTriggerRerun401ResponseError } from './jobs-trigger-rerun401-response-error';

/**
 * 
 * @export
 * @interface JobsTriggerRerun401Response
 */
export interface JobsTriggerRerun401Response {
    /**
     * 
     * @type {JobsTriggerRerun401ResponseError}
     * @memberof JobsTriggerRerun401Response
     */
    'error'?: JobsTriggerRerun401ResponseError;
}

