/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * userCredentials contains connection credentials for connecting to Snowflake. Currently only basic auth (username/password) may be specified. If however, an OAuth connection has been established for the given environment specified in runDetails.environmentID, you may ommit userCredentials. In that case, Coalesce will use the OAuth connection to connect with Snowflake.
 * @export
 * @interface JobsTriggerRerunRequestUserCredentials
 */
export interface JobsTriggerRerunRequestUserCredentials {
    /**
     * Snowflake Account Username. Required when snowflakeAuthType is Basic
     * @type {string}
     * @memberof JobsTriggerRerunRequestUserCredentials
     */
    'snowflakeUsername'?: string;
    /**
     * Snowflake Account password. Required when snowflakeAuthType is Basic
     * @type {string}
     * @memberof JobsTriggerRerunRequestUserCredentials
     */
    'snowflakePassword'?: string;
    /**
     * The PEM-encoded private key to use when authenticating to Snowflake. Required when using the KeyPair authentication type. Newlines must be encoded as \"\\n\" within the request.
     * @type {string}
     * @memberof JobsTriggerRerunRequestUserCredentials
     */
    'snowflakeKeyPairKey'?: string;
    /**
     * The password to use to decrypt the private key. This is only applicable when the authentication type is KeyPair and the private key is encrypted.
     * @type {string}
     * @memberof JobsTriggerRerunRequestUserCredentials
     */
    'snowflakeKeyPairPass'?: string;
    /**
     * Snowflake compute warehouse
     * @type {string}
     * @memberof JobsTriggerRerunRequestUserCredentials
     */
    'snowflakeWarehouse'?: string;
    /**
     * Snowflake user role
     * @type {string}
     * @memberof JobsTriggerRerunRequestUserCredentials
     */
    'snowflakeRole'?: string;
    /**
     * Options: Basic | KeyPair | OAuth
     * @type {string}
     * @memberof JobsTriggerRerunRequestUserCredentials
     */
    'snowflakeAuthType'?: string;
}

