/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobsCancelJobRun401ResponseError } from './jobs-cancel-job-run401-response-error';

/**
 * 
 * @export
 * @interface JobsCancelJobRun401Response
 */
export interface JobsCancelJobRun401Response {
    /**
     * 
     * @type {JobsCancelJobRun401ResponseError}
     * @memberof JobsCancelJobRun401Response
     */
    'error'?: JobsCancelJobRun401ResponseError;
}

