/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobsInitiateRun401ResponseError } from './jobs-initiate-run401-response-error';

/**
 * 
 * @export
 * @interface JobsInitiateRun401Response
 */
export interface JobsInitiateRun401Response {
    /**
     * 
     * @type {JobsInitiateRun401ResponseError}
     * @memberof JobsInitiateRun401Response
     */
    'error'?: JobsInitiateRun401ResponseError;
}

