/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobsGetStatusUpdates401ResponseError } from './jobs-get-status-updates401-response-error';

/**
 * 
 * @export
 * @interface JobsGetStatusUpdates401Response
 */
export interface JobsGetStatusUpdates401Response {
    /**
     * 
     * @type {JobsGetStatusUpdates401ResponseError}
     * @memberof JobsGetStatusUpdates401Response
     */
    'error'?: JobsGetStatusUpdates401ResponseError;
}

