/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobsGetStatusUpdates400ResponseError } from './jobs-get-status-updates400-response-error';

/**
 * 
 * @export
 * @interface JobsGetStatusUpdates400Response
 */
export interface JobsGetStatusUpdates400Response {
    /**
     * 
     * @type {JobsGetStatusUpdates400ResponseError}
     * @memberof JobsGetStatusUpdates400Response
     */
    'error'?: JobsGetStatusUpdates400ResponseError;
}

