/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobsInitiateRunRequestRunDetails } from './jobs-initiate-run-request-run-details';
import { JobsInitiateRunRequestUserCredentials } from './jobs-initiate-run-request-user-credentials';

/**
 * 
 * @export
 * @interface JobsInitiateRunRequest
 */
export interface JobsInitiateRunRequest {
    /**
     * Contains parameters to be used in the Refresh
     * @type {string}
     * @memberof JobsInitiateRunRequest
     */
    'parameters'?: string;
    /**
     * 
     * @type {JobsInitiateRunRequestRunDetails}
     * @memberof JobsInitiateRunRequest
     */
    'runDetails': JobsInitiateRunRequestRunDetails;
    /**
     * 
     * @type {JobsInitiateRunRequestUserCredentials}
     * @memberof JobsInitiateRunRequest
     */
    'userCredentials'?: JobsInitiateRunRequestUserCredentials;
}

