/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobsTriggerRerun400ResponseError } from './jobs-trigger-rerun400-response-error';

/**
 * 
 * @export
 * @interface JobsTriggerRerun400Response
 */
export interface JobsTriggerRerun400Response {
    /**
     * 
     * @type {JobsTriggerRerun400ResponseError}
     * @memberof JobsTriggerRerun400Response
     */
    'error'?: JobsTriggerRerun400ResponseError;
}

