/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobsTriggerRerunRequestRunDetails } from './jobs-trigger-rerun-request-run-details';
import { JobsTriggerRerunRequestUserCredentials } from './jobs-trigger-rerun-request-user-credentials';

/**
 * 
 * @export
 * @interface JobsTriggerRerunRequest
 */
export interface JobsTriggerRerunRequest {
    /**
     * Contains parameters to be used in the Refresh
     * @type {string}
     * @memberof JobsTriggerRerunRequest
     */
    'parameters'?: string;
    /**
     * 
     * @type {JobsTriggerRerunRequestRunDetails}
     * @memberof JobsTriggerRerunRequest
     */
    'runDetails': JobsTriggerRerunRequestRunDetails;
    /**
     * 
     * @type {JobsTriggerRerunRequestUserCredentials}
     * @memberof JobsTriggerRerunRequest
     */
    'userCredentials': JobsTriggerRerunRequestUserCredentials;
}

