/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface JobsGetStatusUpdatesResponse
 */
export interface JobsGetStatusUpdatesResponse {
    /**
     * 
     * @type {string}
     * @memberof JobsGetStatusUpdatesResponse
     */
    'runStatus'?: JobsGetStatusUpdatesResponseRunStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof JobsGetStatusUpdatesResponse
     */
    'runType'?: JobsGetStatusUpdatesResponseRunTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof JobsGetStatusUpdatesResponse
     */
    'runLink'?: string;
}

type JobsGetStatusUpdatesResponseRunStatusEnum = 'completed' | 'initializing' | 'rendering' | 'canceled' | 'failed' | 'running' | 'waitingToRun'
type JobsGetStatusUpdatesResponseRunTypeEnum = 'deploy' | 'refresh'


