/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobsCancelJobRun400ResponseError } from './jobs-cancel-job-run400-response-error';

/**
 * 
 * @export
 * @interface JobsCancelJobRun400Response
 */
export interface JobsCancelJobRun400Response {
    /**
     * 
     * @type {JobsCancelJobRun400ResponseError}
     * @memberof JobsCancelJobRun400Response
     */
    'error'?: JobsCancelJobRun400ResponseError;
}

