/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobsInitiateRun400ResponseError } from './jobs-initiate-run400-response-error';

/**
 * 
 * @export
 * @interface JobsInitiateRun400Response
 */
export interface JobsInitiateRun400Response {
    /**
     * 
     * @type {JobsInitiateRun400ResponseError}
     * @memberof JobsInitiateRun400Response
     */
    'error'?: JobsInitiateRun400ResponseError;
}

