/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Contains the runID to be re-run.
 * @export
 * @interface JobsTriggerRerunRequestRunDetails
 */
export interface JobsTriggerRerunRequestRunDetails {
    /**
     * The number of the run you want to be retried.
     * @type {string}
     * @memberof JobsTriggerRerunRequestRunDetails
     */
    'runID': string;
    /**
     * Allows refreshing an environment even if the last deployment on that environment failed. Use with caution as this can put your environment into an even worse state.
     * @type {boolean}
     * @memberof JobsTriggerRerunRequestRunDetails
     */
    'forceIgnoreWorkspaceStatus'?: boolean;
}

