/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * The error message.
     * @type {string}
     * @memberof ModelError
     */
    'errorString': string;
    /**
     * Additional detail about the error.
     * @type {string}
     * @memberof ModelError
     */
    'errorDetail'?: string;
}

