/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TestRunOrder } from './test-run-order';

/**
 * 
 * @export
 * @interface NodeTest
 */
export interface NodeTest {
    /**
     * 
     * @type {string}
     * @memberof NodeTest
     */
    'description': string;
    /**
     * 
     * @type {boolean}
     * @memberof NodeTest
     */
    'continueOnFailure': boolean;
    /**
     * 
     * @type {string}
     * @memberof NodeTest
     */
    'name': string;
    /**
     * 
     * @type {TestRunOrder}
     * @memberof NodeTest
     */
    'runOrder': TestRunOrder;
    /**
     * 
     * @type {string}
     * @memberof NodeTest
     */
    'templateString': string;
}

