/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Node } from './node';
import { NodeSummary } from './node-summary';

/**
 * @type NodesResponseData
 * A collection of nodes for an environment.
 * @export
 */
export type NodesResponseData = Array<NodeSummary> | Array<Node>;


