/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NodeType } from './node-type';

/**
 * 
 * @export
 * @interface NodeSummary
 */
export interface NodeSummary {
    /**
     * 
     * @type {string}
     * @memberof NodeSummary
     */
    'database': string;
    /**
     * 
     * @type {string}
     * @memberof NodeSummary
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof NodeSummary
     */
    'locationName': string;
    /**
     * 
     * @type {string}
     * @memberof NodeSummary
     */
    'name': string;
    /**
     * 
     * @type {NodeType}
     * @memberof NodeSummary
     */
    'nodeType': NodeType;
    /**
     * 
     * @type {string}
     * @memberof NodeSummary
     */
    'schema': string;
}

