/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BaseNode } from './base-node';
import { NodeType } from './node-type';

/**
 * @type Node
 * @export
 */
export type Node = { type: 'sourceInput' } & SourceNode | { type: 'sql' } & SQLNode;


