/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Package release information for an update operation.
 * @export
 * @interface PackageUpdateReleaseInfo
 */
export interface PackageUpdateReleaseInfo {
    /**
     * 
     * @type {string}
     * @memberof PackageUpdateReleaseInfo
     */
    'version': string;
    /**
     * 
     * @type {string}
     * @memberof PackageUpdateReleaseInfo
     */
    'changeLog': string;
    /**
     * 
     * @type {string}
     * @memberof PackageUpdateReleaseInfo
     */
    'releaseID': string;
}

