/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RefreshRunDetails
 */
export interface RefreshRunDetails {
    /**
     * 
     * @type {boolean}
     * @memberof RefreshRunDetails
     */
    'canceled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RefreshRunDetails
     */
    'environmentID': string;
    /**
     * 
     * @type {string}
     * @memberof RefreshRunDetails
     */
    'excludeNodesSelector'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RefreshRunDetails
     */
    'forceIgnoreEnvironmentStatus'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RefreshRunDetails
     */
    'includeNodesSelector'?: string;
    /**
     * 
     * @type {number}
     * @memberof RefreshRunDetails
     */
    'jobID'?: number;
    /**
     * 
     * @type {number}
     * @memberof RefreshRunDetails
     */
    'parallelism'?: number;
    /**
     * 
     * @type {string}
     * @memberof RefreshRunDetails
     */
    'refreshDescription'?: string;
    /**
     * 
     * @type {number}
     * @memberof RefreshRunDetails
     */
    'nodesForRefresh'?: number;
    /**
     * 
     * @type {number}
     * @memberof RefreshRunDetails
     */
    'nodesInRun'?: number;
}

