/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RunStatus } from './run-status';
import { RunType } from './run-type';

/**
 * 
 * @export
 * @interface RunSummary
 */
export interface RunSummary {
    /**
     * The run ID.
     * @type {number}
     * @memberof RunSummary
     */
    'id': number;
    /**
     * If this is a re-run, the ID of the original operation.
     * @type {string}
     * @memberof RunSummary
     */
    'reRunID'?: string;
    /**
     * The datetime at which the run started.
     * @type {string}
     * @memberof RunSummary
     */
    'runStartTime'?: string;
    /**
     * The datetime at which the run ended.
     * @type {string}
     * @memberof RunSummary
     */
    'runEndTime'?: string;
    /**
     * 
     * @type {RunType}
     * @memberof RunSummary
     */
    'runType': RunType;
    /**
     * 
     * @type {RunStatus}
     * @memberof RunSummary
     */
    'runStatus': RunStatus;
    /**
     * The environment in which the run operation was applied.
     * @type {string}
     * @memberof RunSummary
     */
    'environmentID'?: string;
    /**
     * Information about the cause of a run failure.
     * @type {string}
     * @memberof RunSummary
     */
    'runFailureReason'?: string;
}

