/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrderByDirection } from './order-by-direction';
import { RunsOrderBy } from './runs-order-by';
import { RunsResponseData } from './runs-response-data';

/**
 * A collection of runs.
 * @export
 * @interface RunsResponse
 */
export interface RunsResponse {
    /**
     * The maximum number of runs returned by this query.
     * @type {number}
     * @memberof RunsResponse
     */
    'limit': number;
    /**
     * The sort order for query results.
     * @type {OrderByDirection}
     * @memberof RunsResponse
     */
    'orderByDirection': OrderByDirection;
    /**
     * The field used to sort query results.
     * @type {RunsOrderBy}
     * @memberof RunsResponse
     */
    'orderBy': RunsOrderBy;
    /**
     * 
     * @type {RunsResponseData}
     * @memberof RunsResponse
     */
    'data': RunsResponseData;
}

