/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserConnectionType } from './user-connection-type';

/**
 * Information about the Snowflake account used to perform a run.
 * @export
 * @interface SnowflakeUserCredentials
 */
export interface SnowflakeUserCredentials {
    /**
     * 
     * @type {string}
     * @memberof SnowflakeUserCredentials
     */
    'snowflakeAccount': string;
    /**
     * 
     * @type {UserConnectionType}
     * @memberof SnowflakeUserCredentials
     */
    'snowflakeAuthType': UserConnectionType;
    /**
     * 
     * @type {string}
     * @memberof SnowflakeUserCredentials
     */
    'snowflakeRole'?: string;
    /**
     * 
     * @type {string}
     * @memberof SnowflakeUserCredentials
     */
    'snowflakeUsername': string;
    /**
     * 
     * @type {string}
     * @memberof SnowflakeUserCredentials
     */
    'snowflakeWarehouse'?: string;
}

