/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SourceColumnReferenceV2
 */
export interface SourceColumnReferenceV2 {
    /**
     * 
     * @type {string}
     * @memberof SourceColumnReferenceV2
     */
    'transform': string;
}

