/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomSQL } from './custom-sql';
import { JoinCondition } from './join-condition';
import { RefLink } from './ref-link';

/**
 * 
 * @export
 * @interface SourceMap
 */
export interface SourceMap {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SourceMap
     */
    'aliases'?: { [key: string]: string; };
    /**
     * 
     * @type {CustomSQL}
     * @memberof SourceMap
     */
    'customSQL'?: CustomSQL;
    /**
     * 
     * @type {Array<RefLink>}
     * @memberof SourceMap
     */
    'dependencies': Array<RefLink>;
    /**
     * 
     * @type {JoinCondition}
     * @memberof SourceMap
     */
    'join': JoinCondition;
    /**
     * 
     * @type {string}
     * @memberof SourceMap
     */
    'name': string;
    /**
     * 
     * @type {Array<RefLink>}
     * @memberof SourceMap
     */
    'noLinkRefs': Array<RefLink>;
}

