/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ColumnMetadata } from './column-metadata';
import { SourceColumnMetadataJoin } from './source-column-metadata-join';
import { SourceMap } from './source-map';

/**
 * 
 * @export
 * @interface SourceColumnMetadata
 */
export interface SourceColumnMetadata {
    /**
     * 
     * @type {Array<ColumnMetadata>}
     * @memberof SourceColumnMetadata
     */
    'columns': Array<ColumnMetadata>;
    /**
     * 
     * @type {SourceColumnMetadataJoin}
     * @memberof SourceColumnMetadata
     */
    'join'?: SourceColumnMetadataJoin;
    /**
     * 
     * @type {Array<SourceMap>}
     * @memberof SourceColumnMetadata
     */
    'sourceMapping'?: Array<SourceMap>;
}

