/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ColumnReference } from './column-reference';

/**
 * 
 * @export
 * @interface SourceColumnReferenceV1
 */
export interface SourceColumnReferenceV1 {
    /**
     * 
     * @type {Array<ColumnReference>}
     * @memberof SourceColumnReferenceV1
     */
    'columnReferences': Array<ColumnReference>;
    /**
     * 
     * @type {string}
     * @memberof SourceColumnReferenceV1
     */
    'transform': string;
}

