/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ColumnReference } from './column-reference';
import { SourceColumnReferenceV1 } from './source-column-reference-v1';
import { SourceColumnReferenceV2 } from './source-column-reference-v2';

/**
 * @type SourceColumnReference
 * @export
 */
export type SourceColumnReference = SourceColumnReferenceV1 | SourceColumnReferenceV2;


