/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ColumnMetadata } from './column-metadata';
import { NodeTest } from './node-test';
import { SQLNodeMetadataMappingValue } from './sqlnode-metadata-mapping-value';
import { SourceMap } from './source-map';

/**
 * 
 * @export
 * @interface SQLNodeMetadata
 */
export interface SQLNodeMetadata {
    /**
     * 
     * @type {string}
     * @memberof SQLNodeMetadata
     */
    'description'?: string;
    /**
     * 
     * @type {Array<NodeTest>}
     * @memberof SQLNodeMetadata
     */
    'appliedNodeTests': Array<NodeTest>;
    /**
     * 
     * @type {Array<ColumnMetadata>}
     * @memberof SQLNodeMetadata
     */
    'columns': Array<ColumnMetadata>;
    /**
     * 
     * @type {string}
     * @memberof SQLNodeMetadata
     */
    'cteString'?: string;
    /**
     * 
     * @type {string}
     * @memberof SQLNodeMetadata
     */
    'destinationName'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SQLNodeMetadata
     */
    'enabledColumnTestIDs': Array<string>;
    /**
     * 
     * @type {{ [key: string]: SQLNodeMetadataMappingValue; }}
     * @memberof SQLNodeMetadata
     */
    'mapping'?: { [key: string]: SQLNodeMetadataMappingValue; };
    /**
     * 
     * @type {string}
     * @memberof SQLNodeMetadata
     */
    'materializationOption'?: string;
    /**
     * 
     * @type {Array<SourceMap>}
     * @memberof SQLNodeMetadata
     */
    'sourceMapping': Array<SourceMap>;
}

