/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * @type SQLNodeMetadataMappingValue
 * @export
 */
export type SQLNodeMetadataMappingValue = object | string | number | boolean;


