/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TagColor
 */
export interface TagColor {
    /**
     * 
     * @type {string}
     * @memberof TagColor
     */
    'backgroundColor'?: string;
    /**
     * 
     * @type {string}
     * @memberof TagColor
     */
    'textColor'?: string;
}

