/*
Coalesce API

REST API for performing operations with the Coalesce backend.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Summary information about a user.
 * @export
 * @interface UserSummary
 */
export interface UserSummary {
    /**
     * 
     * @type {string}
     * @memberof UserSummary
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof UserSummary
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSummary
     */
    'lastName'?: string;
}

